# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [81]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [82]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

### Step 3. Assign it to a variable called chipo.

In [83]:
chipo = pd.read_csv(url, sep='\t')

In [84]:
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [85]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

# Name of the max valued product

In [86]:
chipo['item_price'] = list(map(lambda x: float(x.replace('$', '')), chipo['item_price']))

In [87]:
# chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)

chipo['item_price'].info()

<class 'pandas.Series'>
RangeIndex: 4622 entries, 0 to 4621
Series name: item_price
Non-Null Count  Dtype
--------------  -----
4622 non-null   float64
dtypes: float64(1)
memory usage: 36.2 KB

In [88]:
chipo['item_price'].max()

np.float64(44.25)

In [89]:
chipo[['item_price', 'item_name']].sort_values(by='item_price', ascending=False).head(1)

      item_price                     item_name
3598       44.25  Chips and Fresh Tomato Salsa

### Step 4. How many products cost more than $10.00?

In [90]:
mask = chipo.item_price > 10

chipo.item_price[mask]

4       16.98
5       10.98
7       11.75
13      11.25
23      10.98
        ...
4610    11.75
4611    11.25
4617    11.75
4618    11.75
4619    11.25
Name: item_price, Length: 1130, dtype: float64

In [91]:
chipo.item_price[mask].count()

np.int64(1130)

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [92]:
chipo[['item_name', 'item_price']]

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [93]:
chipo['item_name'].sort_values().unique()

<StringArray>
[                    '6 Pack Soft Drink',
                         'Barbacoa Bowl',
                      'Barbacoa Burrito',
                 'Barbacoa Crispy Tacos',
                   'Barbacoa Salad Bowl',
                   'Barbacoa Soft Tacos',
                         'Bottled Water',
                                  'Bowl',
                               'Burrito',
                           'Canned Soda',
                     'Canned Soft Drink',
                         'Carnitas Bowl',
                      'Carnitas Burrito',
                 'Carnitas Crispy Tacos',
                        'Carnitas Salad',
                   'Carnitas Salad Bowl',
                   'Carnitas Soft Tacos',
                          'Chicken Bowl',
                       'Chicken Burrito',
                  'Chicken Crispy Tacos',
                         'Chicken Salad',
                    'Chicken Salad Bowl',
                    'Chicken Soft Tacos',
                                 'Chips',
          'Chips and Fresh Tomato Salsa',
                   'Chips and Guacamole',
     'Chips and Mild Fresh Tomato Salsa',
    'Chips and Roasted Chili Corn Salsa',
    'Chips and Roasted Chili-Corn Salsa',
 'Chips and Tomatillo Green Chili Salsa',
   'Chips and Tomatillo Red Chili Salsa',
 'Chips and Tomatillo-Green Chili Salsa',
   'Chips and Tomatillo-Red Chili Salsa',
                          'Crispy Tacos',
                                  'Izze',
                      'Nantucket Nectar',
                                 'Salad',
                         'Side of Chips',
                            'Steak Bowl',
                         'Steak Burrito',
                    'Steak Crispy Tacos',
                           'Steak Salad',
                      'Steak Salad Bowl',
                      'Steak Soft Tacos',
                           'Veggie Bowl',
                        'Veggie Burrito',
                   'Veggie Crispy Tacos',
                          'Veggie Salad',
                     'Veggie Salad Bowl',
                     'Veggie Soft Tacos']
Length: 50, dtype: str

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

V1

In [94]:
chipo.item_price.sort_values(ascending=False).head(1)

3598    44.25
Name: item_price, dtype: float64

In [95]:
chipo[['item_price', 'quantity']].sort_values(by='item_price', ascending=False).head(1)

      item_price  quantity
3598       44.25        15

V2

In [96]:
chipo[['item_price', 'quantity']].sort_values(by='item_price', ascending=False).head(1).quantity

3598    15
Name: quantity, dtype: int64

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [97]:
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [98]:
mask = chipo['item_name'] == 'Veggie Salad Bowl'

chipo[['quantity', 'item_name']][mask].count()

quantity     18
item_name    18
dtype: int64

In [99]:
len(chipo[['quantity', 'item_name']][mask])

18

### Step 9. How many times did someone order more than one Canned Soda?

In [100]:
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [101]:
chipo[['item_name', 'quantity']].sort_values(by='quantity', ascending=False)[chipo.item_name == 'Canned Soda'][chipo.quantity > 1].count()

C:\Users\pablo\AppData\Local\Temp\ipykernel_17236\2306104933.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  chipo[['item_name', 'quantity']].sort_values(by='quantity', ascending=False)[chipo.item_name == 'Canned Soda'][chipo.quantity > 1].count()
C:\Users\pablo\AppData\Local\Temp\ipykernel_17236\2306104933.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  chipo[['item_name', 'quantity']].sort_values(by='quantity', ascending=False)[chipo.item_name == 'Canned Soda'][chipo.quantity > 1].count()

item_name    20
quantity     20
dtype: int64

In [102]:
chipo[['item_name', 'quantity']].sort_values(by='quantity', ascending=False)[chipo.item_name == 'Canned Soda'][chipo.quantity > 1]

C:\Users\pablo\AppData\Local\Temp\ipykernel_17236\2138363953.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  chipo[['item_name', 'quantity']].sort_values(by='quantity', ascending=False)[chipo.item_name == 'Canned Soda'][chipo.quantity > 1]
C:\Users\pablo\AppData\Local\Temp\ipykernel_17236\2138363953.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  chipo[['item_name', 'quantity']].sort_values(by='quantity', ascending=False)[chipo.item_name == 'Canned Soda'][chipo.quantity > 1]

        item_name  quantity
2235  Canned Soda         4
162   Canned Soda         2
171   Canned Soda         2
51    Canned Soda         2
698   Canned Soda         2
700   Canned Soda         2
1091  Canned Soda         2
1092  Canned Soda         2
350   Canned Soda         2
352   Canned Soda         2
909   Canned Soda         2
2905  Canned Soda         2
2906  Canned Soda         2
3152  Canned Soda         2
1944  Canned Soda         2
3364  Canned Soda         2
3592  Canned Soda         2
18    Canned Soda         2
3866  Canned Soda         2
2135  Canned Soda         2